@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


Person(dev, "Cliente/Frontend")

Container_Boundary(api, "Spring Boot API") {

    Component(securityConfig, "SecurityConfig", "Java",  "Configura autenticação, filtros, permissões e rotas públicas")

    Component(jwtService, "JwtService", "Java + JJWT", "Gera e valida tokens JWT")

    Component(jwtFilter, "JwtFilter", "Java + Spring Security", "Intercepta requisições, lê Authorization header\n e autentica via JWT")

    Component(authUseCase, "AuthUseCaseImpl", "Java", "Valida usuário e retorna token")

    Component(usuarioRepository, "UsuarioRepositoryImpl", "Spring Data JPA", "Busca usuário por email")
}

dev -> securityConfig : Envia requisições
securityConfig -> jwtFilter : Registra filtro
jwtFilter -> jwtService : Valida token JWT
jwtFilter -> usuarioRepository : Busca usuário autenticado
authUseCase -> jwtService : Gera token no login

@enduml
